#:import SlideTransition kivy.uix.screenmanager.SlideTransition
#:import NoTransition kivy.uix.screenmanager.NoTransition

<Name_des_werts@Label>
    background_color: 1,1,1, 0.1
    canvas.before:
        Rectangle:
            pos: self.pos
            size: self.size
        #source: 'HD_rahmen.png'
    font_size: 30
    size_hint: 1, 0.3
    color: 0,0,0,1
    valign: 'bottom'

<Wert@Label>:
    font_size: 40
    color: 1,1,1,1
    text_size: self.size
    halign: 'right'
    valign: 'middle'

<Einheit@Label>:
    font_size: 40
    color: 1,1,1,1
    text_size: self.size
    halign: 'left'
    valign: 'middle'
############
# Anzeige
############
<CAN_Wert_Anzeige>:
    BoxLayout:
        orientation: 'vertical'
        #canvas.after:
        #    Rectangle:
        #        pos: self.pos
        #        size: self.size
                #source: 'HD_rahmen.png'
        Name_des_werts:
            id: n1
            text: 'Name'
        BoxLayout:
            Wert:
                id: w1
                text: 'Wert'
            Einheit:
                id: e1
                text: ' Einheit'

###### Hauptfenster ######
<Hauptbildschirm>:
    BoxLayout:
        orientation: 'vertical'
        Label:
            id: l1
            text: ''

        BoxLayout:
            size_hint: 1,0.2
            Button:
                text: "Konfiguration"
                on_release:
                    root.manager.transition = NoTransition()
                    app.root.current="bsk"
            Button:
                text: "Canwerte anzeigen"
                on_release:
                    root.manager.transition = NoTransition()
                    app.root.current="bs1cw"
            Button:
                text: 'Schliessen'
                on_release: app.stop()

###### Konfigurationsfenster ######
<Bildschirm_Konfiguration>:
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: 'Konfiguration'
        BoxLayout:
            size_hint: 1,0.2
            Button:
                text: 'zurück'
                on_release:
                    root.manager.transition = NoTransition()
                    app.root.current="hbs"
            Button:
                text: 'DBC Datei laden'


###### Bildschirm1 Canwerte ######

<Bildschirm1_Canwerte>:
    BoxLayout:
        orientation: 'vertical'
        Label:
            size_hint: 1,0.1
            text: 'CAN Werte Fenster 1'
        GridLayout:
            name: 'botschaft'
            rows: 2
            padding: 1
            spacing: 1
            CAN_Wert_Anzeige:
                id: a1
            CAN_Wert_Anzeige:
                id: a2
            CAN_Wert_Anzeige:
                id: a3
            CAN_Wert_Anzeige:
                id: a4
        BoxLayout:
            size_hint: 1,0.2
            Button:
                text: 'zurück'
                on_release:
                    root.manager.transition = NoTransition()
                    app.root.current="hbs"
            Button:
                text: 'Weitere Canwerte'
                on_release:
                    root.manager.transition = NoTransition()
                    app.root.current="bs2cw"

###### Bildschirm2 Canwerte ######

<Bildschirm2_Canwerte>:
    BoxLayout:
        orientation: 'vertical'
        Label:
            size_hint: 1,0.1
            text: 'CAN Werte Fenster 2'
        GridLayout:
            name: 'botschaft'
            rows: 2
            padding: 1
            spacing: 1
            CAN_Wert_Anzeige:
                id: a1
            CAN_Wert_Anzeige:
                id: a2
            CAN_Wert_Anzeige:
                id: a3
            CAN_Wert_Anzeige:
                id: a4
        BoxLayout:
            size_hint: 1,0.2
            Button:
                text: 'zurück'
                on_release:
                    root.manager.transition = NoTransition()
                    app.root.current="bs1cw"
            Button:
                text: 'Hauptbilschirm'
                on_release:
                    root.manager.transition = NoTransition()
                    app.root.current="bsew"

###### Bildschirm für Einzelwert anzeige ######

<Bildschirm_Einzelwert>:
    BoxLayout:
        orientation: 'vertical'
        Name_des_werts:
            id: ew_n
            text: 'Bildschirm Einzelwert'
            font_size: 60
        BoxLayout:
            Wert:
                id: w1
                text: 'wert'
                font_size: 100
            Einheit:
                id: ew_e
                text: 'Einheit'
                font_size: 100

###### ROOT ######
Bildschirmverwalter:
    Hauptbildschirm:
        name: "hbs"
        id: s1
    Bildschirm_Konfiguration:
        name: 'bsk'
    Bildschirm1_Canwerte:
        name: 'bs1cw'
    Bildschirm2_Canwerte:
        name: 'bs2cw'
    Bildschirm_Einzelwert:
        name: 'bsew'